{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 5}, "tests": {"0": {"status": "ERROR", "message": "@pytest.fixture(scope=\"session\")\n    def altdriver():\n>       altdriver = AltDriver()\n\nTestsPython\\tests\\conftest.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\altdriver.py:101: in __init__\n    self._connection.connect()\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:314: in connect\n    self._check_close_message(last_close_message)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = WebsocketConnection('127.0.0.1', 13000, 'altws', {'appName': '__default__', 'platform': 'unknown', 'platformVersion': 'unknown', 'deviceInstanceId': 'unknown', 'appId': 'unknown', 'driverType': 'SDK'}, 60)\nclose_message = (4009, 'Limit exceeded, your license supports max. 1 drivers at a time. Get more: https://alttester.com/tools/#pricing')\n\n    def _check_close_message(self, close_message):\n        if close_message:\n            reason = close_message[1]\n    \n            if close_message[0] == 4001:\n                raise exceptions.NoAppConnected(reason)\n            if close_message[0] == 4002:\n                raise exceptions.AppDisconnectedError(reason)\n            if close_message[0] == 4005:\n                raise exceptions.MultipleDriverError(reason)\n            if close_message[0] == 4007:\n                raise exceptions.MultipleDriversTryingToConnectException(\n                    reason)\n            if close_message[0] == 4009:\n>               raise exceptions.MaxNoOfConnectionsDriversExceeded(\n                    reason)\nE               AttributeError: module 'alttester.exceptions' has no attribute 'MaxNoOfConnectionsDriversExceeded'. Did you mean: 'MaxNoOfConnectionsDriversExceededException'?\n\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:221: AttributeError\n", "test_name": "test_game_play_page_displayed_correctly", "rerun": "0"}, "1": {"status": "ERROR", "message": "@pytest.fixture(scope=\"session\")\n    def altdriver():\n>       altdriver = AltDriver()\n\nTestsPython\\tests\\conftest.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\altdriver.py:101: in __init__\n    self._connection.connect()\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:314: in connect\n    self._check_close_message(last_close_message)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = WebsocketConnection('127.0.0.1', 13000, 'altws', {'appName': '__default__', 'platform': 'unknown', 'platformVersion': 'unknown', 'deviceInstanceId': 'unknown', 'appId': 'unknown', 'driverType': 'SDK'}, 60)\nclose_message = (4009, 'Limit exceeded, your license supports max. 1 drivers at a time. Get more: https://alttester.com/tools/#pricing')\n\n    def _check_close_message(self, close_message):\n        if close_message:\n            reason = close_message[1]\n    \n            if close_message[0] == 4001:\n                raise exceptions.NoAppConnected(reason)\n            if close_message[0] == 4002:\n                raise exceptions.AppDisconnectedError(reason)\n            if close_message[0] == 4005:\n                raise exceptions.MultipleDriverError(reason)\n            if close_message[0] == 4007:\n                raise exceptions.MultipleDriversTryingToConnectException(\n                    reason)\n            if close_message[0] == 4009:\n>               raise exceptions.MaxNoOfConnectionsDriversExceeded(\n                    reason)\nE               AttributeError: module 'alttester.exceptions' has no attribute 'MaxNoOfConnectionsDriversExceeded'. Did you mean: 'MaxNoOfConnectionsDriversExceededException'?\n\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:221: AttributeError\n", "test_name": "test_game_can_be_paused_and_resumed", "rerun": "0"}, "2": {"status": "ERROR", "message": "@pytest.fixture(scope=\"session\")\n    def altdriver():\n>       altdriver = AltDriver()\n\nTestsPython\\tests\\conftest.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\altdriver.py:101: in __init__\n    self._connection.connect()\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:314: in connect\n    self._check_close_message(last_close_message)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = WebsocketConnection('127.0.0.1', 13000, 'altws', {'appName': '__default__', 'platform': 'unknown', 'platformVersion': 'unknown', 'deviceInstanceId': 'unknown', 'appId': 'unknown', 'driverType': 'SDK'}, 60)\nclose_message = (4009, 'Limit exceeded, your license supports max. 1 drivers at a time. Get more: https://alttester.com/tools/#pricing')\n\n    def _check_close_message(self, close_message):\n        if close_message:\n            reason = close_message[1]\n    \n            if close_message[0] == 4001:\n                raise exceptions.NoAppConnected(reason)\n            if close_message[0] == 4002:\n                raise exceptions.AppDisconnectedError(reason)\n            if close_message[0] == 4005:\n                raise exceptions.MultipleDriverError(reason)\n            if close_message[0] == 4007:\n                raise exceptions.MultipleDriversTryingToConnectException(\n                    reason)\n            if close_message[0] == 4009:\n>               raise exceptions.MaxNoOfConnectionsDriversExceeded(\n                    reason)\nE               AttributeError: module 'alttester.exceptions' has no attribute 'MaxNoOfConnectionsDriversExceeded'. Did you mean: 'MaxNoOfConnectionsDriversExceededException'?\n\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:221: AttributeError\n", "test_name": "test_game_can_be_paused_and_stopped", "rerun": "0"}, "3": {"status": "ERROR", "message": "@pytest.fixture(scope=\"session\")\n    def altdriver():\n>       altdriver = AltDriver()\n\nTestsPython\\tests\\conftest.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\altdriver.py:101: in __init__\n    self._connection.connect()\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:314: in connect\n    self._check_close_message(last_close_message)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = WebsocketConnection('127.0.0.1', 13000, 'altws', {'appName': '__default__', 'platform': 'unknown', 'platformVersion': 'unknown', 'deviceInstanceId': 'unknown', 'appId': 'unknown', 'driverType': 'SDK'}, 60)\nclose_message = (4009, 'Limit exceeded, your license supports max. 1 drivers at a time. Get more: https://alttester.com/tools/#pricing')\n\n    def _check_close_message(self, close_message):\n        if close_message:\n            reason = close_message[1]\n    \n            if close_message[0] == 4001:\n                raise exceptions.NoAppConnected(reason)\n            if close_message[0] == 4002:\n                raise exceptions.AppDisconnectedError(reason)\n            if close_message[0] == 4005:\n                raise exceptions.MultipleDriverError(reason)\n            if close_message[0] == 4007:\n                raise exceptions.MultipleDriversTryingToConnectException(\n                    reason)\n            if close_message[0] == 4009:\n>               raise exceptions.MaxNoOfConnectionsDriversExceeded(\n                    reason)\nE               AttributeError: module 'alttester.exceptions' has no attribute 'MaxNoOfConnectionsDriversExceeded'. Did you mean: 'MaxNoOfConnectionsDriversExceededException'?\n\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:221: AttributeError\n", "test_name": "test_avoiding_obstacles", "rerun": "0"}, "4": {"status": "ERROR", "message": "@pytest.fixture(scope=\"session\")\n    def altdriver():\n>       altdriver = AltDriver()\n\nTestsPython\\tests\\conftest.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\altdriver.py:101: in __init__\n    self._connection.connect()\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:314: in connect\n    self._check_close_message(last_close_message)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = WebsocketConnection('127.0.0.1', 13000, 'altws', {'appName': '__default__', 'platform': 'unknown', 'platformVersion': 'unknown', 'deviceInstanceId': 'unknown', 'appId': 'unknown', 'driverType': 'SDK'}, 60)\nclose_message = (4009, 'Limit exceeded, your license supports max. 1 drivers at a time. Get more: https://alttester.com/tools/#pricing')\n\n    def _check_close_message(self, close_message):\n        if close_message:\n            reason = close_message[1]\n    \n            if close_message[0] == 4001:\n                raise exceptions.NoAppConnected(reason)\n            if close_message[0] == 4002:\n                raise exceptions.AppDisconnectedError(reason)\n            if close_message[0] == 4005:\n                raise exceptions.MultipleDriverError(reason)\n            if close_message[0] == 4007:\n                raise exceptions.MultipleDriversTryingToConnectException(\n                    reason)\n            if close_message[0] == 4009:\n>               raise exceptions.MaxNoOfConnectionsDriversExceeded(\n                    reason)\nE               AttributeError: module 'alttester.exceptions' has no attribute 'MaxNoOfConnectionsDriversExceeded'. Did you mean: 'MaxNoOfConnectionsDriversExceededException'?\n\nC:\\Users\\QA\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\alttester\\_websocket.py:221: AttributeError\n", "test_name": "test_player_dies_when_obstacles_not_avoided", "rerun": "0"}}, "suite_name": "TestsPython/tests/game_play_test.py"}}}, "date": "November 20, 2024", "start_time": 1732115876.2346618, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "5", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "5"}